version: '3'
services:
  api:
    build: ./
    restart: always
    depends_on:
      - "postgres"
    environment:
      - backend_token=${backend_token}
    env_file:
      - .env
    networks:
      front_net:

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      default:

networks:
  front_net:
    external: true

