version: '3'
services:
  api:
    build: ./
    restart: always
    environment:
      - backend_token=123456
    depends_on:
      - "postgres"
    env_file:
      - .variables.env
    ports:
      - "8080:80"
    networks:
      default:

  postgres:
    image: postgres
    restart: always
    env_file:
      - .variables.env
    networks:
      default:
